def Usage():
	print("Commands : ")
	print("+----------------------------------------------------------+")
	print("|Num|Command |     Descibe                                 |")
	print("+----------------------------------------------------------+")
	print("|0. | help   |    Get Usage(This Page)                     |")
	print("|1. | shell  |    Get into the Single Shell                |")
	print("|2. | send   |    Send a Command to All servers            |")
	print("|3. | down   |    Download the source code and Data        |")
	print("|4. | upload |    Upload a file to the website             |")
	print("|5. | log    |    Download the log of WebServer            |")
	print("|6. | script |    Get the Attack Script list               |")
	print("+----------------------------------------------------------+")
	print("You Can type Num or Command to enter the Function which you want\n")
def Print_Welcome_Message():  #输出欢迎信息
	print("+---------------------------------------+")
	print("|             AWD Framework             |")
	print("+---------------------------------------+")
	print("|            Made By AdianGg            |")
	print("|   AdianGg's Blog:www.e-wolf.top       |")
	print("|         WgpSec:www.wgpsec.org         |")
	print("|               Have Fun                |")
	print("+---------------------------------------+")
def Scriptlist():
	pass