def Usage():
	print("Commands : ")
	print("+----------------------------------------------------------+")
	print("|Num|Command |     Descibe                                 |")
	print("+----------------------------------------------------------+")
	print("|1. | Help   |    Get Usage(This Page)                     |")
	print("|2. | Shell  |    Get into the Single Shell                |")
	print("|3. | Send   |    Send a Command to All servers            |")
	print("|4. | Down   |    Download the source code of all websites |")
	print("|5. | Upload |    Upload a file to the website             |")
	print("|6. | Monitor|    File modification monitoring             |")
	print("|7. | Log    |    Download the log of WebServer            |")
	print("+----------------------------------------------------------+")
def Print_Welcome_Message():  #输出欢迎信息
	print("+---------------------------------------+")
	print("|             AWD Framework             |")
	print("+---------------------------------------+")
	print("|            Made By AdianGg            |")
	print("|   AdianGg's Blog:www.e-wolf.top       |")
	print("|         WgpSec:www.wgpsec.org         |")
	print("|               Have Fun                |")
	print("+---------------------------------------+")